XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates

install:
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/VIP
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/MVVM-C
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/TCA
	cp -R VIP $(XCODE_USER_TEMPLATES_DIR)
	cp -R MVVM-C $(XCODE_USER_TEMPLATES_DIR)
	cp -R TCA $(XCODE_USER_TEMPLATES_DIR)

uninstall:
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/VIP
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/MVVM-C
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/TCA
