XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates

install_templates:
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/VIP
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/MVVMC
	cp -R VIP $(XCODE_USER_TEMPLATES_DIR)
	cp -R MVVMC $(XCODE_USER_TEMPLATES_DIR)

uninstall_templates:
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/VIP
	rm -fR $(XCODE_USER_TEMPLATES_DIR)/MVVMC
